import RegisterCard from "@/Components/Card/RegisterCard";
import React from "react";
export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};
const register = () => {
  return (
    <div>
      <RegisterCard></RegisterCard>
    </div>
  );
};

export default register;
