import LoginCard from "@/Components/Card/LoginCard";
import React from "react";
export const metadata = {
  title: "LogIn",
  description: "Generated by create next app",
};
const Login = () => {
  return (
    <div>
      <LoginCard></LoginCard>
    </div>
  );
};

export default Login;
